platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: diego-release
  - name: diego-release-master
  - name: diego-ci

outputs:
  - name: merged-master

run:
  path: diego-ci/tasks/merge-master-into-develop/task
