---
platform: linux

inputs:
- name: diego-ci
- name: diego-release
- name: golang-release
outputs:
- name: updated-diego-release
- name: pr-message

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

params:
  secret_access_key: ~
  access_key_id: ~

run:
  path: diego-ci/tasks/update-golang-packages/task
