---
# Copied from cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: toolsmiths-env
- name: cf-deployment-concourse-tasks
- name: diego-ci # - This repo
- name: release

run:
  path: diego-ci/tasks/bosh-upload-release/task
