---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: diego-ci
  - name: diego-release
  - name: garden-runc-release-github-release
  - name: garden-runc-release-master

outputs:
  - name: diego-release

run:
  path: diego-ci/tasks/bump_garden_submodules
