---
platform: linux

image_resource:
  type: docker-image
  source: {repository: alpine}

outputs:
- name: tag

params:
  GO_VERSION:

run:
  path: sh
  args:
  - -c
  - |
    cat <<HERE > $PWD/tag/tag
    ${GO_VERSION}
    HERE
    cat <<HERE > $PWD/tag/build-args
    { "go_version": "${GO_VERSION}" }
    HERE
