#!/bin/bash

set -e -x

WORKDIR=$PWD

TAG=$(cat release-tarball/version)

# switch release repo to tag determined by tarball version
pushd release-master
  git fetch --tags
  git checkout "$TAG" || git checkout "v$TAG"
  git submodule update --init --recursive
popd

cp -r release-master/. release-output
