---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: release-tarball
  - name: release-master
  - name: diego-ci

outputs:
  - name: release-output

run:
  path: diego-ci/tasks/checkout-release/task
