---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline
    tag: latest

inputs:
  - name: diego-release-master
  - name: diego-release
  - name: diego-ci
  - name: version

outputs:
  - name: final-release

params:
  secret_access_key: ~
  access_key_id: ~

run:
  path: diego-ci/tasks/create-final-release/task
