#!/bin/bash

setup_mount() {
  local env_name=$1
  local bbl_state_bucket=$2
  local scripts_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  local env_dir="$scripts_dir/../envs/${env_name}"

  if [ -d "${env_dir}" ]; then
    fusermount -u "${env_dir}"
    rm -rf "${env_dir}"
  fi
  mkdir -p "${env_dir}"

  lpass status 2>&1 > /dev/null;
  if [[ $? -ne 0 ]]; then
    echo "Login to lastpass: 'lpass login ...'";
    exit 1
  fi

  tmp_file=$(mktemp -t gcp-service-account-key-XXX)
  trap "rm -rf ${tmp_file}" EXIT
  bosh int <(lpass show --notes "pipeline-secrets") --path "/gcp-service-account-key" > $tmp_file

  GOOGLE_APPLICATION_CREDENTIALS=$tmp_file gcsfuse  "${bbl_state_bucket}" "${env_dir}"

  script='tmp_dir=$(mktemp -d -t bbl-XXX)
  trap "rm -rf ${tmp_dir}" EXIT

  tar xf $(basename $PWD) -C "${tmp_dir}" bbl-state.json vars/

  eval "$(bbl --state-dir ${tmp_dir} print-env)"
  '

  echo "${script}" > "${env_dir}/.envrc"
}

setup_mount "lts-workers-director" "lts-workers-bbl-state"
