#!/bin/bash

set -e -x -u

version=`cat version/number`

pushd routing-release
  bosh --parallel 4 -n create release --with-tarball --version $version --force

  mv dev_releases/routing/*.tgz ../created-routing-release
popd

