#!/bin/bash

set -e -x -u

if [ -z "$ENVIRONMENT_NAME" ]; then
  environment_path="${PWD}/${DEPLOYMENTS_DIR}"
else
  environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
fi

stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

pushd cf-release
  ./scripts/generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/cf/*.yml \
    > ../generated-manifest/cf-deployment.yml
popd

pushd diego-release
  cp ../generated-manifest/cf-deployment.yml /tmp/cf.yml

  ./scripts/generate-deployment-manifest \
    -c /tmp/cf.yml \
    -i ${stubs_path}/diego/iaas-settings.yml \
    -p ${stubs_path}/diego/property-overrides.yml \
    -n ${stubs_path}/diego/instance-count-overrides.yml \
    -v ${stubs_path}/diego/release-versions.yml \
    -s ${stubs_path}/diego/diego-sql.yml -x \
    -R \
    -Q \
    > ../generated-manifest/diego-deployment.yml
popd

pushd routing-release
  cp ./generated-manifest/diego-deployment.yml /tmp/diego.yml
  ./scripts/generate-deployment-manifest \
    -c /tmp/cf.yml \
    -d /tmp/diego.yml \
    -l ${stubs_path}/routing/iaas-settings.yml,\
    ${stubs_path}/routing/instance-count-overrides.yml,\
    ${stubs_path}/routing/persistent-disk-overrides.yml,\
    ${stubs_path}/routing/property-overrides.yml \
    > ../generated-manifest/routing-deployment.yml
popd
