---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
- name: diego-ci
- name: cf-deployment
- name: diego-release-master
- name: diego-final-releases

outputs:
  - name: generated-release

run:
  path: diego-ci/tasks/generate-github-release/task
