platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: diego-release
  - name: diego-ci

run:
  path: diego-ci/tasks/check-diego-release/task

params:
  FORCE_SUBMODULE_HTTPS: true
