---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: diego-ci
- name: grace-config

outputs:
- name: updated-diego-ci

run:
  path: sh
  args:
  - -c
  - |
    checksum=$(jq .grace_tarball_checksum ./grace-config/grace-config.json)

    cp -a diego-ci updated-diego-ci

    cat <<HERE > updated-diego-ci/diego-ci/vars-files/grace-config-vars.yml
    grace_tarball_checksum: ${checksum}
    HERE

    cd updated-diego-ci/diego-ci/

    echo "----- Set git identity"
    git config user.email "cf-diego+github@pivotal.io"
    git config user.name "CI (Automated)"

    echo "----- Update grace checksum"
    git add -A
    git commit -m "Update grace checksum"

    echo "----- DEBUG: show the commit we just created"
    git --no-pager show HEAD
